- name: Install flask for python
  become: yes
  pip:
    name: flask
    state: latest

- name: Create the /dev directory for the packsible-dev-server
  become: yes
  file:
    state: directory
    path: /dev

- name: Copy dev server into /usr/local/bin
  become: yes
  copy:
    src: server.py
    dest: /usr/local/bin/packsible-dev-server
    mode: 0755
