- name: Copy global gitignore
  become: yes
  copy:
    src: gitignore_global
    dest: /etc/gitignore_global
    mode: 0644

- name: Setup global gitignore
  become: yes
  command: git config --global core.excludesfile /etc/gitignore_global

- name: Install flask for python
  become: yes
  pip:
    name: flask
    state: latest

- name: Setup the /packsible directory for the packsible-dev-server
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /packsible
    - /packsible/presetup

- name: Copy dev server into /usr/local/bin
  become: yes
  copy:
    src: server.py
    dest: /usr/local/bin/packsible-dev-server
    mode: 0755
